spring.application.name=Home Server

server.port=8080

storage.location=./file-storage
storage.max-file-size-bytes=524288000

spring.servlet.multipart.max-file-size=520MB
spring.servlet.multipart.max-request-size=520MB
spring.servlet.multipart.enabled=true

storage.allowed-extensions=txt,csv,md,pdf,doc,docx,xls,xlsx,ppt,pptx,png,jpg,jpeg,gif,zip
